/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesSerialKeyboardsRouteImport } from './routes/articles/serial/keyboards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSerialKeyboardsRoute = ArticlesSerialKeyboardsRouteImport.update({
  id: '/articles/serial/keyboards',
  path: '/articles/serial/keyboards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/serial/keyboards': typeof ArticlesSerialKeyboardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/serial/keyboards': typeof ArticlesSerialKeyboardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/serial/keyboards': typeof ArticlesSerialKeyboardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/articles/serial/keyboards'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articles/serial/keyboards'
  id: '__root__' | '/' | '/articles/serial/keyboards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesSerialKeyboardsRoute: typeof ArticlesSerialKeyboardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/serial/keyboards': {
      id: '/articles/serial/keyboards'
      path: '/articles/serial/keyboards'
      fullPath: '/articles/serial/keyboards'
      preLoaderRoute: typeof ArticlesSerialKeyboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesSerialKeyboardsRoute: ArticlesSerialKeyboardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
