/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesNOTAiritoutRouteImport } from './routes/articles/NOT/airitout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNOTAiritoutRoute = ArticlesNOTAiritoutRouteImport.update({
  id: '/articles/NOT/airitout',
  path: '/articles/NOT/airitout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/NOT/airitout': typeof ArticlesNOTAiritoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/NOT/airitout': typeof ArticlesNOTAiritoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/NOT/airitout': typeof ArticlesNOTAiritoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/articles/NOT/airitout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/articles/NOT/airitout'
  id: '__root__' | '/' | '/articles/NOT/airitout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesNOTAiritoutRoute: typeof ArticlesNOTAiritoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/NOT/airitout': {
      id: '/articles/NOT/airitout'
      path: '/articles/NOT/airitout'
      fullPath: '/articles/NOT/airitout'
      preLoaderRoute: typeof ArticlesNOTAiritoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesNOTAiritoutRoute: ArticlesNOTAiritoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
