/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesSerialKeyboardsRouteImport } from './routes/articles/serial/keyboards'
import { Route as ArticlesSerialIloveshoppingRouteImport } from './routes/articles/serial/iloveshopping'
import { Route as ArticlesSerialCovetRouteImport } from './routes/articles/serial/covet'
import { Route as ArticlesSerialAnumberoutofplaceRouteImport } from './routes/articles/serial/anumberoutofplace'
import { Route as ArticlesSerialSerialRouteImport } from './routes/articles/serial/Serial'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSerialKeyboardsRoute = ArticlesSerialKeyboardsRouteImport.update({
  id: '/articles/serial/keyboards',
  path: '/articles/serial/keyboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSerialIloveshoppingRoute =
  ArticlesSerialIloveshoppingRouteImport.update({
    id: '/articles/serial/iloveshopping',
    path: '/articles/serial/iloveshopping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesSerialCovetRoute = ArticlesSerialCovetRouteImport.update({
  id: '/articles/serial/covet',
  path: '/articles/serial/covet',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSerialAnumberoutofplaceRoute =
  ArticlesSerialAnumberoutofplaceRouteImport.update({
    id: '/articles/serial/anumberoutofplace',
    path: '/articles/serial/anumberoutofplace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesSerialSerialRoute = ArticlesSerialSerialRouteImport.update({
  id: '/articles/serial/Serial',
  path: '/articles/serial/Serial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/serial/Serial': typeof ArticlesSerialSerialRoute
  '/articles/serial/anumberoutofplace': typeof ArticlesSerialAnumberoutofplaceRoute
  '/articles/serial/covet': typeof ArticlesSerialCovetRoute
  '/articles/serial/iloveshopping': typeof ArticlesSerialIloveshoppingRoute
  '/articles/serial/keyboards': typeof ArticlesSerialKeyboardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/serial/Serial': typeof ArticlesSerialSerialRoute
  '/articles/serial/anumberoutofplace': typeof ArticlesSerialAnumberoutofplaceRoute
  '/articles/serial/covet': typeof ArticlesSerialCovetRoute
  '/articles/serial/iloveshopping': typeof ArticlesSerialIloveshoppingRoute
  '/articles/serial/keyboards': typeof ArticlesSerialKeyboardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/serial/Serial': typeof ArticlesSerialSerialRoute
  '/articles/serial/anumberoutofplace': typeof ArticlesSerialAnumberoutofplaceRoute
  '/articles/serial/covet': typeof ArticlesSerialCovetRoute
  '/articles/serial/iloveshopping': typeof ArticlesSerialIloveshoppingRoute
  '/articles/serial/keyboards': typeof ArticlesSerialKeyboardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/serial/Serial'
    | '/articles/serial/anumberoutofplace'
    | '/articles/serial/covet'
    | '/articles/serial/iloveshopping'
    | '/articles/serial/keyboards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/serial/Serial'
    | '/articles/serial/anumberoutofplace'
    | '/articles/serial/covet'
    | '/articles/serial/iloveshopping'
    | '/articles/serial/keyboards'
  id:
    | '__root__'
    | '/'
    | '/articles/serial/Serial'
    | '/articles/serial/anumberoutofplace'
    | '/articles/serial/covet'
    | '/articles/serial/iloveshopping'
    | '/articles/serial/keyboards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesSerialSerialRoute: typeof ArticlesSerialSerialRoute
  ArticlesSerialAnumberoutofplaceRoute: typeof ArticlesSerialAnumberoutofplaceRoute
  ArticlesSerialCovetRoute: typeof ArticlesSerialCovetRoute
  ArticlesSerialIloveshoppingRoute: typeof ArticlesSerialIloveshoppingRoute
  ArticlesSerialKeyboardsRoute: typeof ArticlesSerialKeyboardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/serial/keyboards': {
      id: '/articles/serial/keyboards'
      path: '/articles/serial/keyboards'
      fullPath: '/articles/serial/keyboards'
      preLoaderRoute: typeof ArticlesSerialKeyboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/serial/iloveshopping': {
      id: '/articles/serial/iloveshopping'
      path: '/articles/serial/iloveshopping'
      fullPath: '/articles/serial/iloveshopping'
      preLoaderRoute: typeof ArticlesSerialIloveshoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/serial/covet': {
      id: '/articles/serial/covet'
      path: '/articles/serial/covet'
      fullPath: '/articles/serial/covet'
      preLoaderRoute: typeof ArticlesSerialCovetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/serial/anumberoutofplace': {
      id: '/articles/serial/anumberoutofplace'
      path: '/articles/serial/anumberoutofplace'
      fullPath: '/articles/serial/anumberoutofplace'
      preLoaderRoute: typeof ArticlesSerialAnumberoutofplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/serial/Serial': {
      id: '/articles/serial/Serial'
      path: '/articles/serial/Serial'
      fullPath: '/articles/serial/Serial'
      preLoaderRoute: typeof ArticlesSerialSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesSerialSerialRoute: ArticlesSerialSerialRoute,
  ArticlesSerialAnumberoutofplaceRoute: ArticlesSerialAnumberoutofplaceRoute,
  ArticlesSerialCovetRoute: ArticlesSerialCovetRoute,
  ArticlesSerialIloveshoppingRoute: ArticlesSerialIloveshoppingRoute,
  ArticlesSerialKeyboardsRoute: ArticlesSerialKeyboardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
